name: Check Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          path: /home/linuxbrew/.linuxbrew
          key: ${{ runner.os }}-homebrew-${{ hashFiles('**/Brewfile.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-homebrew-

      - name: Set up Homebrew
        if: steps.cache-homebrew.outputs.cache-hit != 'true'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup environment
        run: |
          make setup

      - name: Run pre-commit hooks
        run: make format
